# Generated by Django 5.0.4 on 2024-04-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_alter_document_options_documentstatuschange'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
