# Generated by Django 5.0.4 on 2024-04-09 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_documentstatus'),
        ('notifications', '0009_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentstatus',
            options={'verbose_name': 'Статус документа', 'verbose_name_plural': 'Статусы документов'},
        ),
        migrations.CreateModel(
            name='CustomNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.NOTIFICATIONS_NOTIFICATION_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.document')),
            ],
            options={
                'verbose_name': 'Пользовательское уведомление',
                'verbose_name_plural': 'Пользовательские уведомления',
            },
            bases=('notifications.notification',),
        ),
    ]
